### ISSUE TITLE
Broken on VS2022  > 17.3.3

### ISSUE THREAD

**Issue by lucasbenhur** [Elders/VSE-FormatDocumentOnSave#47] opened 2022-09-01 16:32 UTC
Latest update from VS seems to have broken this extension unfortunately.
No longer formatting document when I edit.

My settings are set at the default.

**Comment by valentasm1** [comment] 2022-09-02 09:28
Same

**Comment by mynkow** [comment] 2022-09-02 18:39
🤕 Will check it on Monday...

**Comment by mynkow** [comment] 2022-09-07 09:17
Hmm, it is working for me. It just takes 1-2 minutes VS2022 to load all extensions. Once loaded it is working.

Could you please check that? If this is the case we can't do anything. The other options is to take a look at the VS logs and see for errors there.

**Comment by valentasm1** [comment] 2022-09-07 09:30
How to know when extensions is loaded?
At first i thought it is resharper but then i disable it and it still dont format on save.

**Comment by lucasbenhur** [comment] 2022-09-08 04:08
I waited 1-2 min, but it didn't work.

I also tried:
- Reset visual studio settings.
- Re-install extension

Unsuccessfully!

**Comment by lumicompell** [comment] 2022-09-09 11:31
<time>2022/09/09 11:23:12.610</time>
<type>Information</type>
<source>Extension Manager</source>
<description>Successfully loaded extension &apos;Format document on Save&apos; (2f4fac85-be4e-4d7a-8c74-93cc4389b427)...</description>

There is no errors in my logs, but the extension is not working.

**Comment by mynkow** [comment] 2022-09-09 12:00
Hey, great news. It stopped working for me as well. Just like that. No idea why. It is really...

**Comment by mynkow** [comment] 2022-09-12 09:30
Here is what I have found. And I do not think we could fix it at all. When you edit a file and save it, the extension captures the action and formats the document before being saved. This is possible because of the events coming from VS. However, the document is actually saved before throwing the event. See the screenshot bellow:

![image](https://user-images.githubusercontent.com/183151/189620597-c0aa141a-5dae-4048-9a4d-09cfa964a4c1.png)

**Comment by valentasm1** [comment] 2022-09-14 10:18
Did you wrote smth to MS? 
Now extension works again in 17.3.4 version

**Comment by mynkow** [comment] 2022-09-19 06:28
Woooow, this is madness. I am glad they have fixed that.

**Comment by valentasm1** [comment] 2022-09-19 06:44
It was working. Now it is not again. I think it works sometimes and sometimes not.
Anyone else could confirm it works for them?

**Comment by lumicompell** [comment] 2022-09-19 07:20
It was working after updating to 17.3.4.
It is not working after updating winOS and rebooting.

**Comment by mynkow** [comment] 2022-09-22 21:12
I have added steps to reproduce to MS. I doubt that they will fix this.

https://developercommunity.visualstudio.com/t/Visual-Studio-clears-dirty-flag-before-c/10124978#T-N10148841-N10155655

**Comment by mus65** [comment] 2022-09-23 07:39
We also hit this, but we found an alternative which makes the whole extension obsolete, at least for our use cases. In "Options -> Text Editor -> Code Cleanup" there is an option "Run Code Cleanup profile on save".  If you include the fixer "Format document" in the configured profile you basically have the same functionality this extension provides.

**Comment by valentasm1** [comment] 2022-09-23 09:30
@mus65 I dont want be a bummer about this extension but your suggestion is great. I dont need this extension anymore :). I havent heard about it but looks usefull, simple and customizable. I just missing more explanation on some formatting

**Comment by lumicompell** [comment] 2022-09-23 09:56
Code Cleanup is not working for me.

**Comment by WolfgangVogl** [comment] 2022-09-23 12:25
Yes, again - Clang Power Tools (format on save) and this extension (format document on save) no longer work and Code Cleanup doesn't work either. VERY VERY ANNOYING.

**Comment by valentasm1** [comment] 2022-09-26 16:24
@Krusty93 i think sync setting is also doable or at least in close future. Check it out more here
https://github.com/dotnet/roslyn/issues/40163

**Comment by mynkow** [comment] 2022-09-27 10:57
I am working on a workaround. ;)

**Comment by Alexolut** [comment] 2022-09-28 16:08
It seems that extension now work again for VS 17.3.5

**Comment by mynkow** [comment] 2022-09-29 06:30
It is still not working on my end. This is strange.

**Comment by WolfgangVogl** [comment] 2022-09-29 06:54
> It is still not working on my end. This is strange.

For me, formatting on save works with the VS Update to 17.3.5. I'm not sure if it is this extension or one of the others (Clang power tools, ...). If you instruct me how to find out which one does the job I would be happy to share this information with you.

**Comment by dlehn** [comment] 2022-09-29 07:21
I just tested this myself. VS 17.3.5 does not fix the issue, but the Format on Save option of Clang Power Tools 2022 does work.

**Comment by mynkow** [comment] 2022-09-29 09:25
@WolfgangVogl you can go and disable an extension without uninstalling it. I think it requires a VS restart.

**Comment by mynkow** [comment] 2022-09-29 09:39
Hey everyone, I have a workaround implemented in the version attached to this comment. I you think it works properly I will upload it to the extension store. Please give any feedback.

[Elders.VSE_FormatDocumentOnSave.vsix.zip](https://github.com/Elders/VSE-FormatDocumentOnSave/files/9673329/Elders.VSE_FormatDocumentOnSave.vsix.zip)

**Comment by dlehn** [comment] 2022-09-29 09:55
Thanks for the fix! 
So I just tried it on 17.3.5 and the formatting works again now. However it does seem to have the same issue Clang Power Tools has, where it introduces some additional undo steps. 
After saving, you have to hit undo twice in order to undo the formatting, then there is an additional undo that seemingly does nothing and only after that will you begin undoing the changes you made before saving.

It's not a huge issue overall, but it's still weird behavior. I'm also pretty sure this was never the case in VS2019, can't say how it was before in VS2022 since I only upgraded a few days ago.

**Comment by aligature** [comment] 2022-09-29 18:13
Still appears to be broken for me on 17.3.5.

**Comment by aligature** [comment] 2022-09-29 18:23
> Hey everyone, I have a workaround implemented in the version attached to this comment. If you think it works properly I will upload it to the extension store. Please give any feedback.
> 
> [Elders.VSE_FormatDocumentOnSave.vsix.zip](https://github.com/Elders/VSE-FormatDocumentOnSave/files/9673329/Elders.VSE_FormatDocumentOnSave.vsix.zip)

I gave this version a try and it seems to be functional based on my spot testing.

**Comment by aligature** [comment] 2022-09-29 18:37
> > Hey everyone, I have a workaround implemented in the version attached to this comment. If you think it works properly I will upload it to the extension store. Please give any feedback.
> > [Elders.VSE_FormatDocumentOnSave.vsix.zip](https://github.com/Elders/VSE-FormatDocumentOnSave/files/9673329/Elders.VSE_FormatDocumentOnSave.vsix.zip)
> 
> I gave this version a try and it seems to be functional based on my spot testing.

On further testing I'm seeing a weird issue where I sporadic pop up dialogs prompting me to save an unknown file as filename "Output-Build.txt". Sometimes I get many of these pop ups in a row. The pop ups go away when I disable the experimental extension.

**Comment by dlehn** [comment] 2022-09-29 18:43
> On further testing I'm seeing a weird issue where I sporadic pop up dialogs prompting me to save an unknown file as filename "Output-Build.txt". Sometimes I get many of these pop ups in a row. The pop ups go away when I disable the experimental extension.

Interesting, this happened to me as well. Though it stopped after I restarted VS (at least so far), didn't make the connection that it might be related to the extension.

**Comment by WolfgangVogl** [comment] 2022-09-29 18:44
I'll give it a try tomorrow.
Like dlehn already mentioned the clang powertools work but introduce other issues.

https://developercommunity.visualstudio.com/t/Visual-Studio-clears-dirty-flag-before-c/10124978#T-N10148841-N10155655
got reopened and they're asking for more information. I've tried to create a video/gif from a debug session to attach it but for some reason I can't get visual studio to load the debug symbols so the breakpoint isn't hit.

**Comment by WolfgangVogl** [comment] 2022-09-30 08:33
> On further testing I'm seeing a weird issue where I sporadic pop up dialogs prompting me to save an unknown file as filename "Output-Build.txt". Sometimes I get many of these pop ups in a row. The pop ups go away when I disable the experimental extension.

Today I got the pop-up as well. (With the filename "Incredibuild-Output.txt" or something like that (I use Incredibuild to compile, so it seems logical to me).
BUT I did NOT install the experimental fix for this extension - so that doesn't seem to be the cause of the pop-ups?!

**Comment by dlehn** [comment] 2022-10-03 10:11
I used to have that issue when using Tabs Studio, if you hit save with multiple changed documents it would cycle through all the respective tabs while saving them. Haven't had any similar issues since I got rid of that.

**Comment by mynkow** [comment] 2022-10-03 10:12
> I used to have that issue when using Tabs Studio, if you hit save with multiple changed documents it would cycle through all the respective tabs while saving them. Haven't had any similar issues since I got rid of that.

True, this happens when you do `ctrl+shift+s` and it is normal

**Comment by mynkow** [comment] 2022-10-10 06:20
So, should we close this issue?

**Comment by cremor** [comment] 2022-10-10 09:19
I'm using VS 17.3.5 and extension version 3.5. The formatting - so the default functionality of the extension - works.

But I've changed the `Commands` option of the extension to `Edit.FormatDocument Edit.RemoveAndSort` and the `Edit.RemoveAndSort` part doesn't work.

**Comment by cremor** [comment] 2022-10-10 13:22
Oh, and my Visual Studio also often crashes now when I do simple things like Add - New Item - Search for something or just when renaming a folder in the solution explorer. After I restart VS it shows a yellow bar where it blames the FormatDocumentOnSave extension for the crash.

**Comment by mynkow** [comment] 2022-10-10 13:51
Wooow, we have a developer at Microsoft looking into our problem. They still can't reproduce it on their machines for some reason but I have sent a video. Hope this helps them figure this out.

**Comment by obsgolem** [comment] 2022-10-11 15:56
Have you sent them the stack traces I collected on my issue?

**Comment by mynkow** [comment] 2022-10-13 06:17
I am going to revert the hack because it causes event more problems

**Comment by dmitryvhf** [comment] 2022-10-13 11:09
VS 17.4.0 Preview 3.0, VSE v.3.6 - dont work.
VS 17.3.6,  VSE v.3.6 - work ok.

VSE v.3.7 cant install - "Extension already installed"

**Comment by TommyXR** [comment] 2022-10-13 17:25
Since the update, the extension doesn't work for me nor the rest of my team in VS 17.3.6. No crash, but it does nothing.

**Comment by DanielaE** [comment] 2022-10-14 05:00
@dmitryvhf : the .vsix downloaded as VSE **v3.7** contains the identical binaries as the **v3.6** .vsix.

**Comment by cremor** [comment] 2022-10-14 05:17
I just updated from extension version 3.5 to 3.7 but after that VS showed that 3.6 is installed. And as already reported an update from 3.6 to 3.7 doesn't work.

And with 3.6 (or maybe 3.7?) in VS 17.3.6 the extension seems to do nothing.

@dmitryvhf Are you sure that the combination VS 17.3.6 and extension 3.6 works for you?

**Comment by dmitryvhf** [comment] 2022-10-14 06:27
> Are you sure that the combination VS 17.3.6 and extension 3.6 works for you?
@cremor Yes, i sure. Checked few times.

**Comment by sunnamed434** [comment] 2022-10-14 13:52
Working for me with [latest Visual Studio update](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1736--visual-studio-2022-version-1736).

**Comment by Krusty93** [comment] 2022-10-14 15:54
> Working for me with [latest Visual Studio 2022 version 17.3.6](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1736--visual-studio-2022-version-1736).

Still not working here, on 2 different PCs. Have you tried a new project and/or deleted the `.vs` folder or anything else?

**Comment by sunnamed434** [comment] 2022-10-14 16:03
> > Working for me with [latest Visual Studio 2022 version 17.3.6](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#1736--visual-studio-2022-version-1736).
> 
> Still not working here, on 2 different PCs. Have you tried a new project and/or deleted the `.vs` folder or anything else?

Yeah, sad, Extension not working on newer version of projects, .NET Framework and .NET Core (Console apps) not works for me =(

**Comment by mynkow** [comment] 2022-10-18 16:50
Hey everyone,

I have good news. Microsoft were able to reproduce and fix the bug. It will be probably released with the next VS version.

https://developercommunity.visualstudio.com/t/Visual-Studio-clears-dirty-flag-before-c/10124978#T-N10175828

**Comment by obsgolem** [comment] 2022-10-25 19:10
New preview release just dropped. I tested and it appears to be fixed for me.

**Comment by dmitryvhf** [comment] 2022-10-26 06:24
> New preview release just dropped. I tested and it appears to be fixed for me.

Confirm. VS2022 Preview 5, old project. It's working.

**Comment by sunnamed434** [comment] 2022-10-26 10:19
> > New preview release just dropped. I tested and it appears to be fixed for me.
> 
> VS2022 Preview 5, VSE 3.6; old project. Confirm. It's working.

Working fine for me after update too!

**Comment by sunnamed434** [comment] 2022-10-27 09:40
Extension working fine as it intentional, but I got new problem after new visual studio update, see #53

**Comment by mynkow** [comment] 2022-11-09 15:41
I had to push a v3.9 where everything should be working now.

**Closed by mynkow** 2022-11-09 15:41 UTC
